from repositories.categoria_repository import CategoriaRepository
from repositories.projeto_repository import ProjetoRepository
from repositories.registro_repository import RegistroRepository
from repositories.pessoa_repository import PessoaRepository